In [ ]:
#%pip install rpy2

Defaulting to user installation because normal site-packages is not writeable
Collecting rpy2
  Downloading rpy2-3.6.3-py3-none-any.whl.metadata (5.4 kB)
Collecting rpy2-rinterface>=3.6.3 (from rpy2)
  Downloading rpy2_rinterface-3.6.3-cp313-cp313-win_amd64.whl.metadata (1.9 kB)
Collecting rpy2-robjects>=3.6.2 (from rpy2)
  Downloading rpy2_robjects-3.6.2-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: packaging in c:\programdata\anaconda3\lib\site-packages (from rpy2) (24.2)
Requirement already satisfied: cffi>=1.15.1 in c:\programdata\anaconda3\lib\site-packages (from rpy2-rinterface>=3.6.3->rpy2) (1.17.1)
Requirement already satisfied: pycparser in c:\programdata\anaconda3\lib\site-packages (from cffi>=1.15.1->rpy2-rinterface>=3.6.3->rpy2) (2.21)
Requirement already satisfied: jinja2 in c:\programdata\anaconda3\lib\site-packages (from rpy2-robjects>=3.6.2->rpy2) (3.1.6)
Collecting tzlocal (from rpy2-robjects>=3.6.2->rpy2)
  Downloading tzlocal-5.3.1-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: MarkupSafe>=2.0 in c:\programdata\anaconda3\lib\site-packages (from jinja2->rpy2-robjects>=3.6.2->rpy2) (3.0.2)
Requirement already satisfied: tzdata in c:\programdata\anaconda3\lib\site-packages (from tzlocal->rpy2-robjects>=3.6.2->rpy2) (2025.2)
Downloading rpy2-3.6.3-py3-none-any.whl (9.9 kB)
Downloading rpy2_rinterface-3.6.3-cp313-cp313-win_amd64.whl (174 kB)
Downloading rpy2_robjects-3.6.2-py3-none-any.whl (125 kB)
Downloading tzlocal-5.3.1-py3-none-any.whl (18 kB)
Installing collected packages: tzlocal, rpy2-rinterface, rpy2-robjects, rpy2

   ---------- ----------------------------- 1/4 [rpy2-rinterface]
   ---------- ----------------------------- 1/4 [rpy2-rinterface]
   ---------- ----------------------------- 1/4 [rpy2-rinterface]
   -------------------- ------------------- 2/4 [rpy2-robjects]
   -------------------- ------------------- 2/4 [rpy2-robjects]
   -------------------- ------------------- 2/4 [rpy2-robjects]
   ---------------------------------------- 4/4 [rpy2]

Successfully installed rpy2-3.6.3 rpy2-rinterface-3.6.3 rpy2-robjects-3.6.2 tzlocal-5.3.1
Note: you may need to restart the kernel to use updated packages.

In [2]:
import rpy2.robjects as robjects
from rpy2.robjects.conversion import localconverter
from rpy2.robjects import pandas2ri

import pandas as pd

Error importing in API mode: ImportError('On Windows, cffi mode "ANY" is only "ABI".')
Trying to import in ABI mode.

In [10]:
pd.set_option('display.max_columns', None)

In [3]:
readRDS = robjects.r['readRDS']

In [4]:
survey_r = readRDS(r"C:\Users\Peter\OneDrive\Desktop\Code and Projects\ECO1400\Replication Package\Datasets\Survey\survey.rds")
like_user_r = readRDS(r"C:\Users\Peter\OneDrive\Desktop\Code and Projects\ECO1400\Replication Package\Datasets\Likes\likes_user.rds")
fb_user_r = readRDS(r"C:\Users\Peter\OneDrive\Desktop\Code and Projects\ECO1400\Replication Package\Datasets\Extension\facebook\fb_user.rds")
nav_his_user_r = readRDS(r"C:\Users\Peter\OneDrive\Desktop\Code and Projects\ECO1400\Replication Package\Datasets\Extension\navigate/nav_user.rds")
shared_user_r = readRDS(r"C:\Users\Peter\OneDrive\Desktop\Code and Projects\ECO1400\Replication Package\Datasets\Shared\shared_user.rds")

In [5]:
survey_r

<rpy2.robjects.vectors.DataFrame object at 0x000001D4D0D6B290> [19]
R classes: ('data.table', 'data.frame')
[StrSexpVe..., IntSexpVe..., IntSexpVe..., IntSexpVe..., ..., IntSexpVe..., IntSexpVe..., BoolSexpV..., FloatSexp...]
  ResponseId: <class 'rpy2.robjects.vectors.StrVector'>
  <rpy2.robjects.vectors.StrVector object at 0x000001D4C8187550> [16]
R classes: ('character',)
['R_0005Pj..., 'R_0006ze..., 'R_000QQG..., 'R_000QuL..., ..., 'R_zfiOvl..., 'R_zfj2X1..., 'R_zflZX2..., 'R_zfoOiB...]
  treatment: <class 'rpy2.robjects.vectors.FactorVector'>
  <rpy2.robjects.vectors.FactorVector object at 0x000001D4CF234110> [13]
R classes: ('factor',)
[Liberal, Liberal, Liberal, Control, ..., Conse..., Control, Control, Conse...]
  matchTreatment: <class 'rpy2.robjects.vectors.FactorVector'>
  <rpy2.robjects.vectors.FactorVector object at 0x000001D4D0BA8990> [13]
R classes: ('factor',)
[Pro, Counter, Pro, Control, ..., Counter, Control, Control, Pro]
  treatIdeo: <class 'rpy2.robjects.vectors.FactorVector'>
  <rpy2.robjects.vectors.FactorVector object at 0x000001D4D0EFBB90> [13]
R classes: ('factor',)
[treat..., treat..., treat..., control, ..., treat..., control, control, treat...]
...
  potentialText: <class 'rpy2.robjects.vectors.IntVector'>
  <rpy2.robjects.vectors.IntVector object at 0x000001D4D0EFB950> [13]
R classes: ('integer',)
[NA_integer_, 999, NA_integer_, NA_integer_, ..., -1, -1, -1, NA_integer_]
  primaryOutlets: <class 'rpy2.robjects.vectors.IntVector'>
  <rpy2.robjects.vectors.IntVector object at 0x000001D4D0EFB910> [13]
R classes: ('integer',)
[NA_integer_, 1, NA_integer_, NA_integer_, ..., 0, 1, 1, NA_integer_]
  comply: <class 'rpy2.robjects.vectors.BoolVector'>
  <rpy2.robjects.vectors.BoolVector object at 0x000001D4CF1B7E90> [10]
R classes: ('logical',)
[NA,        1, NA,        1, ...,        1,        1,        1, NA]
  newLikesNum: <class 'rpy2.robjects.vectors.POSIXct'>
  <rpy2.robjects.vectors.POSIXct object at 0x000001D4D0EFBFD0> [14]
R classes: ('POSIXct', 'POSIXt')
[NA_charac..., 2018-04-2..., ..., 2018-05-2..., 2018-05-1..., 2018-04-1..., 2018-04-2...]

In [7]:
with localconverter(robjects.default_converter + pandas2ri.converter):
    survey = robjects.conversion.rpy2py(survey_r)
    like_user = robjects.conversion.rpy2py(like_user_r)
    fb_user = robjects.conversion.rpy2py(fb_user_r)
    nav_his_user = robjects.conversion.rpy2py(nav_his_user_r)
    shared_user = robjects.conversion.rpy2py(shared_user_r)

In [8]:
survey

,ResponseId,treatment,matchTreatment,treatIdeo,control,potentialText,primaryOutlets,comply,newLikesNum,tookFollowup,...,F_party7,F_slant_Rep,F_slant_Dem,F_ideology,F_echoChamber,F_whoWillWin,F_vote,F_modifiedViews,F_withoutLastControl,F_startPOSIX
1,R_0005PjATeKpQ5pf,Liberal,Pro,treatLIdeoL,False,"c(""FoxNews"", ""HuffPost"", ""MSNBC"", ""NationalRev...",True,True,1,False,...,NaN,-2147483648,-2147483648,-2147483648,-2147483648,-2147483648,-2147483648,-2147483648,NA,NaT
2,R_0006zeOG7m4r5bX,Liberal,Counter,treatLIdeoC,False,"c(""FoxNews"", ""HuffPost"", ""MSNBC"", ""NationalRev...",True,True,4,True,...,NaN,3,-3,0,1,-1,999,1,True,2018-04-23 13:44:25-04:00
3,R_000QQGgF1fS7UXL,Liberal,Pro,treatLIdeoL,False,"c(""FoxNews"", ""HuffPost"", ""MSNBC"", ""NationalRev...",True,True,4,False,...,NaN,-2147483648,-2147483648,-2147483648,-2147483648,-2147483648,-2147483648,-2147483648,NA,NaT
4,R_000QuLyZsff11wl,Control,Control,control,True,"c(""FoxNews"", ""HuffPost"", ""MSNBC"", ""NationalRev...",True,NA,0,True,...,0.0,-2147483648,-2147483648,-2147483648,-2147483648,-2147483648,-2147483648,-2147483648,True,2018-04-19 11:59:13-04:00
5,R_000vCzLW7tMEGbL,Liberal,Pro,treatLIdeoL,False,"c(""FoxNews"", ""NationalReview"", ""Salon"", ""Slate...",False,False,0,False,...,NaN,-2147483648,-2147483648,-2147483648,-2147483648,-2147483648,-2147483648,-2147483648,NA,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37490,R_zfeiEbwrxA57jrP,Control,Control,control,True,"c(""FoxNews"", ""HuffPost"", ""MSNBC"", ""NationalRev...",True,NA,0,True,...,-3.0,3,-2,-3,3,-1,-1,0,True,2018-05-20 09:57:02-04:00
37491,R_zfiOvlmPfCMWNRn,Conservative,Counter,treatCIdeoL,False,"c(""FoxNews"", ""HuffPost"", ""MSNBC"", ""NationalRev...",True,False,0,True,...,-1.0,3,-1,0,2,999,-1,0,True,2018-05-16 18:23:22-04:00
37492,R_zfj2X1JcX4Yc2Qx,Control,Control,control,True,"c(""FoxNews"", ""HuffPost"", ""MSNBC"", ""NationalRev...",True,NA,0,True,...,-1.0,1,-2,-3,2,-1,-1,1,True,2018-04-19 12:15:59-04:00
37493,R_zflZX23gkgzR2V3,Control,Control,control,True,"c(""FoxNews"", ""MSNBC"", ""NationalReview"", ""Slate...",False,NA,0,True,...,0.0,0,-1,0,2,-1,-1,1,True,2018-04-20 22:34:58-04:00
37494,R_zfoOiBw3bx7UBB7,Conservative,Pro,treatCIdeoC,False,"c(""DailyCaller"", ""HuffPost"", ""MSNBC"", ""Nationa...",False,False,0,False,...,NaN,-2147483648,-2147483648,-2147483648,-2147483648,-2147483648,-2147483648,-2147483648,NA,NaT

In [12]:
survey.describe(include="all")

,ResponseId,treatment,matchTreatment,treatIdeo,control,potentialText,primaryOutlets,comply,newLikesNum,tookFollowup,have14DaysPosts,installTwoWeeks,have14DaysLikes,validExtAndShared,validHisOneWeek,minHistoryRelative,maxTimeExt,maxDiffPostsDay,mobile,politicsAd,follow,followAboveMed,thermo_Rep,thermo_Dem,empathy_Rep,empathy_Dem,certain,certainAboveEqMed,selfReportedLikesNum,slant_Rep,slant_Dem,zipReside,registered,personality_1,personality_2,personality_3,personality_4,personality_5,personality_6,personality_7,personality_8,personality_9,personality_10,immigration,daca,immigrationWorry,thermo_Trump,thermo_TrumpHave,thermo_TrumpWM,thermo_Local,mostNews,mostNewsSM,accessWebsites,crtA,crtB,ideoLeaning,ideoLeaningF,startPOSIX,democrat,republican,independent,ideologyN,thermo_Diff,thermo_DiffAboveEqMed,thermo_DiffHave,thermo_DiffWM,age,ageAboveMed,ageHave,ageWM,female,ideologyF,partyAllF,trumpF,genderF,ageSqWM,immigrationWorryF,MuellerFairF,obstructF,repF,absIdeology,empathyDifficult_Diff,empathyDifficult_DiffHave,empathyDifficult_DiffWM,echoChamber,echoChamberAboveEqMed,openessPersonality,openessPersonalityAboveEqMed,seenCounterAnyShare,seenCounterAnyShareAboveEqMed,initialLikesNum,countInitialNewsLikes,countInitialNewsLikesAboveMed,meanInitialSlant,absInitialSlant,postsInitialAccess,absIdeoAboveEqMed,meanSeenAboveMed,meanDistSlantUnderMed,consIdeology,crtScoreAboveEqMed,clickLinks_Mobile,clickLinks_PC,party7,genericBallotF,thermo_Own,thermo_Opposing,empathyDifficult_Own,empathyDifficult_Opposing,objective,voteSupport2016F,ageSq,rosensteinF,Q_SocialSource,askExtension,F_approve,F_approve_ScaleS,F_favorable_McCabe,F_favorable_McCabe_Op_ScaleS,F_favorable_Hogg,F_favorable_Hogg_Op_ScaleS,F_favorable_Mueller,F_favorable_Mueller_Op_ScaleS,F_favorable_Daniels,F_favorable_Daniels_Op_ScaleS,F_favorable_Bolton,F_favorable_Bolton_Op_ScaleS,F_favorable_Pruitt,F_favorable_Pruitt_Op_ScaleS,F_favorable_Cohen,F_favorable_Cohen_Op_ScaleS,F_favorable_Clinton,F_favorable_Clinton_Op_ScaleS,F_favOrg_NRA,F_favOrg_NRA_Op_ScaleS,F_favOrg_March,F_favOrg_March_Op_ScaleS,F_favOrg_California,F_favOrg_California_Op_ScaleS,F_favOrg_FBI,F_favOrg_FBI_Op_ScaleS,F_mccabe_summary,F_mccabe_summary_ScaleS,F_tradeWar,F_tradeWar_Op_ScaleS,F_gunPolicy_Assault,F_gunPolicy_Assault_Op_ScaleS,F_thermo_Trump,F_thermo_Trump_ScaleS,F_favOrg_Immigrants,F_favOrg_Immigrants_Op_ScaleS,F_investigation,F_investigation_Op_ScaleS,F_BN_Obstruct,F_BN_Obstruct_Op_ScaleS,F_partyIdeasDem,F_partyIdeasRep,F_empathy_difficultDem,F_empathy_difficultRep,F_empathy_importantDem,F_empathy_importantRep,F_thermo_Dem,F_thermo_Rep,F_marryDem,F_marryRep,persIndex,persAnderson,persAndersonNoNeg,persAndersonWithMissing,persAndersonNoNegWithMissing,F_thermo_Diff,F_thermo_DiffScale,F_empathyDifficult_Diff,F_empathyDifficult_DiffScale,F_empathyImportant_Diff,F_empathyImportant_DiffScale,F_partyIdeas_Diff,F_partyIdeas_DiffScale,F_marry_Opposing,F_marry_OpposingScale,F_postMod_Like_Pol,F_postMod_Like_PolScale,F_postMod_Share_Pol,F_postMod_Share_PolScale,F_postMod_ShareActual_Pol,F_postMod_ShareActual_PolScale,polAffectiveIndex,polIndexBehavior,polIndexAll,polAffectiveIndexNoMarry,polAffectiveIndexOwn,polAffectiveIndexOpposing,polAffectiveAnderson,polAffectiveAndersonWithMissing,F_heardNews_Clark,F_heardNews_Clinton,F_favorable_Farrakhan_Know,F_favorable_Cohen_Know,F_believeNews_Wall,F_believeNews_Tax,F_believeNews_CriminalTarget,F_believeNews_Influence,F_party7,F_slant_Rep,F_slant_Dem,F_ideology,F_echoChamber,F_whoWillWin,F_vote,F_modifiedViews,F_withoutLastControl,F_startPOSIX
count,37494,37494,36330,36728,37494,37494,37494,37494,37494.00000,37494,37494,37494.000000,37494,3.749400e+04,3.749400e+04,2214.000000,2228,36743.000000,37494.000000,37494,37494.000000,37494,3.749400e+04,3.749400e+04,3.749400e+04,3.749400e+04,3.749400e+04,37494,3.749400e+04,3.749400e+04,3.749400e+04,37494,3.749400e+04,3.749400e+04,3.749400e+04,3.749400e+04,3.749400e+04,3.749400e+04,3.749400e+04,3.749400e+04,3.749400e+04,3.749400e+04,3.749400e+04,3.749400e+04,3.749400e+04,3.749400e+04,3.749400e+04,37494,37494.000000,3.749400e+04,37494.000000,37494,3.749400e+04,37494,37494,36330.000000,37494,37494,37494.000000,37494.000000,37494.000000,3.749400e+04,3.749400e+04,37494,37494,37494.000000,36260.000000,37494,37494,37494.000000,36585.000000,37494,37494,37494,37494,37494.000000,37494,37494,37494,37494,3.749400e+04,34949.000000,37494,37494.000000,3.749400e+04,37494,37406.000000,37494,34248.000000,37494,37494.000000,37494.000000,37494,32482.000000,32482.000000,37494,37494,37494,37494,37494,3.749400e+04,34500.000000,33009.000000,34394.000000,37494,3.749400e+04,3.749400e+04,35127.000000,36121.000000,37494,37494,36260.000000,37494,37494,37494.000000,3.749400e+04,17626.000000,3.749400e+04,14613.000000,3.749400e+04,14380.000000,3.749400e+04,17027.000000,3.749400e+04,17171.000000,3.749400e+04,14404.000000,3.749400e+04,14919.000000,3.749400e+04,16406.000000,3.749400e+04,17609.000000,3.749400e+04,17597.000000,3.749400e+04,17521.000000,3.749400e+04,17534.000000,3.749400e+04,17564.000000,15011.000000,15011.000000,3.749400e+04,16440.000000,3.749400e+04,17193.000000,3.749400e+04,17262.000000,3.749400e+04,17599.000000,3.749400e+04,17135.000000,3.749400e+04,16408.000000,3.749400e+04,3.749400e+04,3.749400e+04,3.749400e+04,3.749400e+04,3.749400e+04,3.749400e+04,3.749400e+04,3.749400e+04,3.749400e+04,17635.000000,9434.000000,9434.000000,17635.000000,17635.000000,3.749400e+04,16331.000000,16822.000000,16822.000000,3.749400e+04,16816.000000,3.749400e+04,16896.000000,3.749400e+04,10466.000000,16453.000000,16453.000000,16453.000000,16453.000000,10450.000000,10450.000000,16896.000000,17123.000000,17645.000000,16896.000000,16896.000000,16896.000000,10059.000000,16896.000000,3.749400e+04,3.749400e+04,17635.000000,17635.000000,3.749400e+04,3.749400e+04,3.749400e+04,3.749400e+04,15483.000000,3.749400e+04,3.749400e+04,3.749400e+04,3.749400e+04,3.749400e+04,3.749400e+04,3.749400e+04,3.749400e+04,17635
unique,37494,3,3,5,2,1042,2,3,NaN,2,2,NaN,2,3.000000e+00,3.000000e+00,NaN,NaN,NaN,NaN,3,NaN,2,NaN,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN,13551,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,2,NaN,514,749,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,3,2,NaN,NaN,3,2,NaN,NaN,8,8,5,3,NaN,5,4,4,3,NaN,NaN,2,NaN,NaN,3,NaN,3,NaN,3,NaN,NaN,2,NaN,NaN,2,3,3,3,3,3.000000e+00,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,26381,4,NaN,7,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.000000e+00,NaN
top,R_zfoOiBw3bx7UBB7,Control,Counter,control,False,"c(""FoxNews"", ""HuffPost"", ""MSNBC"", ""NationalRev...",True,True,NaN,False,True,NaN,True,-2.147484e+09,-2.147484e+09,NaN,NaN,NaN,NaN,True,NaN,False,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,False,NaN,10,,NaN,liberalIdeo,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,False,True,NaN,NaN,2. Liberal,Strong Democrat,Strongly disapprove,female,NaN,Not at all,Yes,Yes,"Yes, representative name:",NaN,NaN,True,NaN,NaN,True,NaN,True,NaN,True,NaN,NaN,False,NaN,NaN,True,True,False,False,False,-2.147484e+09,NaN,NaN,NaN,The Democratic Party candidate,NaN,NaN,NaN,NaN,,1,NaN,Not familiar with Rod Rosenstein,PoliticsMapAll,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.147484e+09,NaN
freq,1,12502,12126,12502,24992,20772,20772,13258,NaN,19859,34592,NaN,35347,3.253800e+04,3.528000e+04,NaN,NaN,NaN,NaN,22418,NaN,19198,NaN,NaN,NaN,NaN,NaN,31874,NaN,NaN,NaN,177,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37263,NaN,NaN,NaN,30922,NaN,15530,14430,NaN,23691,NaN,NaN,NaN,NaN,NaN,NaN,17540,34789,NaN,NaN,18151,36260,NaN,NaN,10723,10863,24094,18930,NaN,13036,22667,23820,26407,NaN,NaN,34949,NaN,NaN,32236,NaN,19431,NaN,19162,NaN,NaN,20113,NaN,NaN,36673,24370,19692,18367,23691,2.082600e+04,NaN,NaN,NaN,20520,NaN,NaN,NaN,NaN,6821,19692,NaN,9351,10272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.985900e+04,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.70582,NaN,NaN,0.048941,NaN,NaN,NaN,-99217.146793,2018-05-25 15:34:05.316253952+00:00,60.473206,0.670534,NaN,3.348536,NaN,-7.199514e+07,-3.516705e+07,-3.516709e+07,-4.639307e+07,-5.326609e+06,NaN,-8.105041e+08,-4.696567e+06,-5.727531e+06,NaN,-1.219966e+07,-5.956637e+06,-2.291015e+07,-1.288696e+07,-1.483432e+07,-1.237148e+07,-1.282968e+07,-1.408974e+07,-1.512070e+07,-1.523525e+07,-1.403247e+07,-5.784815e+06,-1.775536e+06,-2.291005e+05,-1.323059e+07,NaN,27.812610,-4.477217e+08,3.477836,NaN,-1.128325e+07,NaN,NaN,-0.304211,NaN,2018-02-27 13:00:26.169013760-05:00,0.382088,0.169520,0.365712,-2.812222e+07,-1.549299e+08,NaN,NaN,46.593802,47.694208,NaN,NaN,46.124500,0.517425,NaN,NaN,NaN,NaN,2496.258548,NaN,NaN,NaN,NaN,-2.812222e+07,1.916450,NaN,1.786366,-1.002319e+07,NaN,5.623002,NaN,0.414521,NaN,474.351896,8.109031,NaN,-0.181630,0.539718,NaN,NaN,NaN,NaN,NaN,NaN,8.986646,6.080653,-0.741118,NaN,-8.614213e+07,-1.474841e+08,4.220286,2.284350,NaN,NaN,2581.211197,NaN,NaN,0.215608,-1.137948e+09,0.003360,-1.137432e+09,0.003344,-1.137432e+09,-0.002499,-1.137432e+09,0.007202,-1.137432e+09,0.002690,-1.137432e+09,0.014886,-1.137432e+09,-0.004247,-1.137432e+09,0.010582,-1.137432e+09,0.009879,-1.138578e+09,-0.007693,-1.138864e+09,0.001248,-1.139494e+09,-0.005312,-1.141212e+09,0.000083,-0.414296,-0.004354,-1.147913e+09,0.003645,-1.152037e+09,0.000399,-1.158796e+09,0.001844,-1.138864e+09,0.007496,-1.144362e+09,-0.009821,-1.146882e+09,0.001190,-1.151235e+09,-1.151235e+09,-1.153870e+09,-1.153870e+09,-1.153813e+09,-1.154328e+09,-1.164180e+09,-1.178728e+09,-1.761161e+09,-1.538302e+09,0.001365,0.005876,0.000608,0.005766,0.004059,-1.212119e+09,-0.016821,1.840209,-0.029851,-1.184341e+09,-0.011847,-1.179759e+09,-0.012168,-1.548039e+09,-0.025840,0.361940,0.008805,0.715857,-0.006874,0.912249,-0.011533,-0.025275,-0.001015,-0.021119,-0.022196,-0.011992,0.020027,-0.018991,-0.027308,-1.149116e+09,-1.147226e+09,0.799093,0.930309,-1.147398e+09,-1.146195e+09,-1.147283e+09,-1.147971e+09,-0.927404,-1.173115e+09,-1.173630e+09,-1.174260e+09,-1.175062e+09,-1.156276e+09,-1.154901e+09,-1.162404e+09,NaN,2018-04-29 07:45:14.326906368-04:00
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00000,NaN,NaN,0.000000,NaN,NaN,NaN,-489416.000000,2018-02-04 22:40:07.870000+00:00,-1.000000,0.000000,NaN,0.000000,NaN,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,NaN,-2.147484e+09,-2.147484e+09,-2.147484e+09,NaN,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,NaN,0.000000,-2.147484e+09,1.000000,NaN,-2.147484e+09,NaN,NaN,-1.000000,NaN,2018-02-03 20:41:49-05:00,0.000000,0.000000,0.000000,-2.147484e+09,-2.147484e+09,NaN,NaN,-100.000000,18.000000,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,-2.147484e+09,-4.000000,NaN,-4.000000,-2.147484e+09,NaN,1.000000,NaN,0.000000,NaN,0.000000,0.000000,NaN,-0.998400,0.000050,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,-3.000000,NaN,-2.147484e+09,-2.147484e+09,1.000000,1.000000,NaN,NaN,324.000000,NaN,NaN,0.000000,-2.147484e+09,-0.667872,-2.147484e+09,-1.846714,-2.147484e+09,-1.061502,-2.147484e+09,-0.912925,-2.147484e+09,-1.757806,-2.147484e+09,-0.828746,-2.147484e+09,-0.718328,-2.147484e+09,-0.800437,-2.147484e+09,-1.437325,-2.147484e+09,-0.746328,-2.147484e+09,-0.822713,-2.147484e+09,-1.184357,-2.147484e+09,-1.156904,-1.000000,-0.681918,-2.147484e+09,-1.032978,-2.147484e+09,-0.753041,-2.147484e+09,-0.718929,-2.147484e+09,-1.322218,-2.147484e+09,-0.780809,-2.147484e+09,-0.613108,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-1.396161,-2.511377,-1.404100,-38.557946,-1.888440,-2.147484e+09,-5.214317,-4.000000,-3.628037,-2.147484e+09,-3.595768,-2.147484e+09,-4.523532,-2.147484e+09,-0.893995,0.000000,-0.746226,0.000000,-1.599251,0.000000,-3.290192,-5.591401,-4.758669,-4.722169,-5.377962,-4.096315,-1.715058,-4.235042,-5.389770,-2.147484e+09,-2.147484e+09,0.000000,0.000000,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-3.000000,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,NaN,2018-04-18 11:45:26-04:00
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00000,NaN,NaN,0.000000,NaN,NaN,NaN,-129483.500000,2018-04-02 18:23:31.442499840+00:00,51.000000,0.000000,NaN,3.000000,NaN,2.000000e+00,1.600000e+01,2.000000e+00,1.000000e+00,3.000000e+00,NaN,-2.147484e+09,2.000000e+00,-3.000000e+00,NaN,1.000000e+00,3.000000e+00,2.000000e+00,5.000000e+00,2.000000e+00,5.000000e+00,2.000000e+00,5.000000e+00,1.000000e+00,5.000000e+00,1.000000e+00,-1.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,NaN,1.000000,0.000000e+00,1.000000,NaN,2.000000e+00,NaN,NaN,-1.000000,NaN,2018-02-19 02:02:06.500000-05:00,0.000000,0.000000,0.000000,-2.000000e+00,2.500000e+01,NaN,NaN,25.000000,31.000000,NaN,NaN,30.000000,0.000000,NaN,NaN,NaN,NaN,900.000000,NaN,NaN,NaN,NaN,1.000000e+00,1.000000,NaN,0.000000,1.000000e+00,NaN,5.000000,NaN,0.333333,NaN,141.000000,2.000000,NaN,-0.584600,0.407007,NaN,NaN,NaN,NaN,NaN,NaN,1.500000,0.000000,-3.000000,NaN,5.000000e+01,1.000000e+00,4.000000,1.000000,NaN,NaN,961.000000,NaN,NaN,0.000000,-2.147484e+09,-0.667872,-2.147484e+09,-1.021548,-2.147484e+09,-1.061502,-2.147484e+09,-0.912925,-2.147484e+09,-0.960132,-2.147484e+09,-0.828746,-2.147484e+09,-0.718328,-2.147484e+09,-0.800437,-2.147484e+09,-0.794087,-2.147484e+09,-0.746328,-2.147484e+09,-0.822713,-2.147484e+09,-0.533801,-2.147484e+09,-0.369164,-1.000000,-0.681918,-2.147484e+09,-1.032978,-2.147484e+09,-0.753041,-2.147484e+09,-0.691340,-2.147484e+09,-0.631272,-2.147484e+09,-0.780809,-2.147484e+09,-0.613108,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-0.781543,-0.741398,-0.743699,-0.230888,-0.782540,-2.147484e+09,-0.667541,0.000000,-1.163614,-2.147484e+09,-0.659521,-2.147484e+09,-0.434645,-2.147484e+09,-0.893995,0.000000,-0.746226,0.000000,-1.599251,1.000000,0.303849,-0.721950,-0.100405,-0.682278,-0.706952,-0.619024,-0.716357,-0.765041,-0.772918,-2.147484e+09,-2.147484e+09,1.000000,1.000000,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-3.000000,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,NaN,2018-04-19 13:54:51-04:00
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00000,NaN,NaN,0.000000,NaN,NaN,NaN,-128334.000000,2018-06-28 09:55:26.889000192+00:00,59.000000,1.000000,NaN,3.000000,NaN,1.500000e+01,5.000000e+01,3.000000e+00,2.000000e+00,3.000000e+00,NaN,0.000000e+00,3.000000e+00,-2.000000e+00,NaN,1.000000e+00,5.000000e+00,3.000000e+00,6.000000e+00,3.000000e+00,6.000000e+00,5.000000e+00,6.000000e+00,3.000000e+00,6.000000e+00,2.000000e+00,0.000000e+00,2.000000e+00,1.000000e+00,4.000000e+00,NaN,4.000000,2.000000e+01,3.000000,NaN,4.000000e+00,NaN,NaN,-1.000000,NaN,2018-02-28 21:09:54-05:00,0.000000,0.000000,0.000000,-1.000000e+00,5.000000e+01,NaN,NaN,50.000000,49.000000,NaN,NaN,48.000000,1.000000,NaN,NaN,NaN,NaN,2304.000000,NaN,NaN,NaN,NaN,2.000000e+00,2.000000,NaN,2.000000,1.000000e+00,NaN,6.000000,NaN,0.428571,NaN,295.000000,5.000000,NaN,-0.429120,0.551600,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,2.000000,-1.000000,NaN,6.500000e+01,5.000000e+00,5.000000,2.000000,NaN,NaN,2401.000000,NaN,NaN,0.000000,-2.147484e+09,-0.667872,-2.147484e+09,-0.196383,-2.147484e+09,-0.456045,-2.147484e+09,-0.244766,-2.147484e+09,-0.162457,-2.147484e+09,-0.111156,-2.147484e+09,-0.718328,-2.147484e+09,-0.800437,-2.147484e+09,0.492391,-2.147484e+09,-0.746328,-2.147484e+09,-0.822713,-2.147484e+09,-0.533801,-2.147484e+09,-0.369164,-1.000000,-0.681918,-2.147484e+09,-0.239881,-2.147484e+09,-0.753041,-2.147484e+09,-0.636163,-2.147484e+09,-0.631272,-2.147484e+09,-0.780809,-2.147484e+09,-0.613108,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-0.466249,-0.154301,-0.413738,-0.024102,-0.325703,-2.147484e+09,0.072632,2.000000,0.068597,-2.147484e+09,-0.659521,-2.147484e+09,-0.434645,-2.147484e+09,-0.893995,0.000000,-0.746226,1.000000,0.625183,1.000000,0.303849,-0.014221,0.074777,0.003852,-0.005702,0.100398,-0.120195,-0.061385,-0.084496,-2.147484e+09,-2.147484e+09,1.000000,1.000000,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-1.000000,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,NaN,2018-04-25 16:28:52-04:00
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00000,NaN,NaN,0.000000,NaN,NaN,NaN,-71334.750000,2018-06-30 21:15:51.562249984+00:00,89.000000,1.000000,NaN,4.000000,NaN,5.000000e+01,7.300000e+01,4.000000e+00,3.000000e+00,4.000000e+00,NaN,1.000000e+00,3.000000e+00,-1.000000e+00,NaN,1.000000e+00,6.000000e+00,5.000000e+00,7.000000e+00,5.000000e+00,7.000000e+00,6.000000e+00,7.000000e+00,5.000000e+00,6.000000e+00,4.000000e+00,1.000000e+00,2.000000e+00,2.000000e+00,6.000000e+01,NaN,60.000000,6.600000e+01,6.000000,NaN,5.000000e+00,NaN,NaN,1.000000,NaN,2018-03-07 21:25:23.249999872-05:00,1.000000,0.000000,1.000000,1.000000e+00,7.000000e+01,NaN,NaN,70.000000,63.000000,NaN,NaN,62.000000,1.000000,NaN,NaN,NaN,NaN,3844.000000,NaN,NaN,NaN,NaN,2.000000e+00,3.000000,NaN,3.000000,2.000000e+00,NaN,6.500000,NaN,0.500000,NaN,580.000000,11.000000,NaN,0.260687,0.693421,NaN,NaN,NaN,NaN,NaN,NaN,10.000000,6.000000,1.000000,NaN,7.900000e+01,1.900000e+01,5.000000,3.000000,NaN,NaN,3969.000000,NaN,NaN,0.000000,-2.000000e+00,1.189545,0.000000e+00,0.628783,1.000000e+00,1.360328,1.000000e+00,1.091554,0.000000e+00,0.635218,-1.000000e+00,0.606434,-2.000000e+00,1.002874,-2.000000e+00,1.035575,-1.000000e+00,1.135629,-2.000000e+00,1.092805,1.000000e+00,0.993290,1.000000e+00,1.417869,1.000000e+00,1.206316,0.000000,0.474919,1.000000e+00,1.346314,2.000000e+00,1.032637,2.000000e+00,0.798453,0.000000e+00,0.750619,1.000000e+00,0.437795,1.000000e+00,1.630748,2.000000e+00,1.000000e+00,2.000000e+00,3.000000e+00,4.000000e+00,4.000000e+00,4.900000e+01,1.200000e+01,-2.147484e+09,0.000000e+00,0.987813,0.661188,0.900698,0.222704,0.816835,4.800000e+01,0.707066,3.000000,0.684703,0.000000e+00,0.808603,1.000000e+00,0.587576,0.000000e+00,0.419786,1.000000,1.339841,1.000000,0.625183,1.000000,0.303849,0.674286,1.077712,0.648658,0.665890,0.722401,0.682586,0.675364,0.650638,1.000000e+00,1.000000e+00,1.000000,1.000000,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,0.000000,2.000000e+00,-2.000000e+00,-1.000000e+00,2.000000e+00,1.000000e+00,-1.000000e+00,0.000000e+00,NaN,2018-05-10 07:50:56-04:00

In [16]:
survey["treatment"].isna().sum()

np.int64(0)

In [14]:
survey["polAffectiveIndex"].isna().sum()

np.int64(20598)

In [21]:
like_user

,ResponseId,potLib_Like,potCons_Like,potCounter_Like,potPro_Like
1,R_0006zeOG7m4r5bX,4.0,0.0,4.0,0.0
2,R_000QQGgF1fS7UXL,4.0,0.0,0.0,4.0
3,R_000QuLyZsff11wl,0.0,0.0,0.0,0.0
4,R_000vCzLW7tMEGbL,0.0,0.0,0.0,0.0
5,R_001H4q0zrFzZ77H,0.0,0.0,0.0,0.0
...,...,...,...,...,...
35343,R_zfeiEbwrxA57jrP,0.0,0.0,0.0,0.0
35344,R_zfiOvlmPfCMWNRn,0.0,0.0,0.0,0.0
35345,R_zfj2X1JcX4Yc2Qx,0.0,0.0,0.0,0.0
35346,R_zflZX23gkgzR2V3,0.0,0.0,0.0,0.0
35347,R_zfoOiBw3bx7UBB7,0.0,0.0,0.0,0.0

In [22]:
fb_user

,ResponseId,potLibDay_FB,potLibDay_FBAd,potLibDay_FBFriend,potLibDay_FBPage,potConsDay_FB,potConsDay_FBAd,potConsDay_FBFriend,potConsDay_FBPage,potProDay_FB,...,moderate_FBPage,slant_FB,slant_FBAd,slant_FBFriend,slant_FBPage,slantExcluding_FB,slantExcluding_FBAd,slantExcluding_FBFriend,slantExcluding_FBPage,countAllDay_FB
1,R_00VWiXSyP4IFidX,3.142857,0.142857,2.285714,0.714286,0.214286,0.071429,0.142857,0.000000,3.142857,...,26.0,-0.386814,-0.424926,-0.326772,-0.466132,-0.377328,-0.484700,-0.293001,-0.473197,276.500000
2,R_02tSkPVvgF3ABTb,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.799650,NaN,0.823900,0.775400,0.799650,NaN,0.823900,0.775400,2.357143
3,R_03AZmC2IlNijPwJ,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.214286
4,R_067EGGoT5exHou5,0.214286,0.000000,0.214286,0.000000,0.071429,0.000000,0.071429,0.000000,0.214286,...,0.0,-0.287847,NaN,-0.287847,NaN,-0.268400,NaN,-0.268400,NaN,26.714286
5,R_0AIKY95N8bGyf61,7.642857,1.642857,5.714286,0.285714,0.928571,0.214286,0.714286,0.000000,7.642857,...,2.0,-0.347612,-0.413746,-0.343394,-0.328365,-0.330161,-0.369100,-0.329868,-0.315377,320.357143
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1831,R_zT2fZIuS0hGOXPH,0.500000,0.000000,0.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.500000,...,0.0,-0.369492,-0.529300,-0.362354,-0.542400,-0.343072,-0.529300,-0.333850,-0.542400,111.571429
1832,R_zTr8DSDCI20kErn,10.285714,1.071429,8.928571,0.285714,2.428571,0.214286,2.214286,0.000000,2.428571,...,6.0,-0.284657,-0.374155,-0.265196,-0.441885,-0.279299,-0.287412,-0.264428,-0.422283,299.357143
1833,R_zZ25JNKw53OL6fv,1.642857,0.142857,1.428571,0.071429,0.142857,0.071429,0.071429,0.000000,1.642857,...,1.0,-0.386445,-0.213129,-0.439070,-0.407250,-0.342151,-0.219167,-0.384322,-0.387300,140.285714
1834,R_zc0O5YbLSHr0t2x,0.000000,0.000000,0.000000,0.000000,0.071429,0.000000,0.000000,0.071429,0.071429,...,0.0,0.171500,NaN,NaN,0.171500,-0.354500,NaN,NaN,-0.354500,1.857143
1835,R_zerQInwPfXDcIYV,0.000000,0.000000,0.000000,0.000000,0.142857,0.000000,0.142857,0.000000,0.000000,...,1.0,-0.000325,NaN,0.003452,-0.087200,-0.070845,NaN,-0.070067,-0.087200,86.285714

In [23]:
nav_his_user

,ResponseId,potLib_His,potLib_Nav,potCons_His,potCons_Nav,potPro_His,potPro_Nav,potCounter_His,potCounter_Nav,newLike_His,...,newLike_NavNotFromFB,liberal_NavNotFromFB,conservative_NavNotFromFB,moderate_NavNotFromFB,slant_His,slant_Nav,slantExcluding_His,slantExcluding_Nav,slant_NavFromFB,slant_NavNotFromFB
1,R_00VWiXSyP4IFidX,6.0,0.0,1.0,0.0,6.0,0.0,1.0,0.0,0.0,...,0.0,11.0,5.0,5.0,-0.336009,-0.108677,-0.332095,-0.108677,-0.174460,-0.093014
2,R_02tSkPVvgF3ABTb,2.0,2.0,3.0,0.0,3.0,0.0,2.0,2.0,0.0,...,0.0,4.0,47.0,59.0,0.759012,0.251800,0.761736,0.261528,NaN,0.251800
3,R_03AZmC2IlNijPwJ,46.0,6.0,3.0,3.0,46.0,6.0,3.0,3.0,2.0,...,3.0,93.0,8.0,13.0,-0.269872,-0.250946,-0.255165,-0.246745,NaN,-0.250946
4,R_067EGGoT5exHou5,6.0,3.0,1.0,0.0,6.0,3.0,1.0,0.0,0.0,...,0.0,10.0,1.0,9.0,-0.164433,-0.242305,-0.127513,-0.183683,-0.127000,-0.248070
5,R_0AIKY95N8bGyf61,140.0,73.0,9.0,3.0,140.0,73.0,9.0,3.0,0.0,...,0.0,162.0,12.0,18.0,-0.368791,-0.407686,-0.344660,-0.327123,-0.310016,-0.444821
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1831,R_zT2fZIuS0hGOXPH,31.0,1.0,3.0,0.0,31.0,1.0,3.0,0.0,0.0,...,0.0,17.0,0.0,1.0,-0.304628,-0.285000,-0.285833,-0.274087,-0.148371,-0.338133
1832,R_zTr8DSDCI20kErn,703.0,92.0,14.0,3.0,14.0,3.0,703.0,92.0,1.0,...,0.0,101.0,2.0,6.0,-0.422328,-0.440061,-0.295027,-0.293698,-0.223623,-0.491689
1833,R_zZ25JNKw53OL6fv,30.0,1.0,0.0,0.0,30.0,1.0,0.0,0.0,0.0,...,0.0,31.0,0.0,55.0,-0.525550,-0.279318,-0.582100,-0.275559,-0.322740,-0.276793
1834,R_zc0O5YbLSHr0t2x,1.0,2.0,0.0,5.0,0.0,5.0,1.0,2.0,0.0,...,5.0,17.0,7.0,1.0,-0.405575,-0.134622,-0.404357,-0.367647,NaN,-0.134622
1835,R_zerQInwPfXDcIYV,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.0,0.0,1.0,-0.206714,-0.325550,-0.206714,-0.325550,NaN,-0.325550

In [24]:
shared_user

,ResponseId,potLib_Shared,potLib_SharedBefore,potLib_SharedBeforeEmpty,potLib_SharedEmpty,potCons_Shared,potCons_SharedBefore,potCons_SharedBeforeEmpty,potCons_SharedEmpty,potPro_Shared,...,moderateDay_SharedBeforeEmpty,moderateDay_SharedEmpty,slant_Shared,slant_SharedBefore,slant_SharedBeforeEmpty,slant_SharedEmpty,slantExcluding_Shared,slantExcluding_SharedBefore,slantExcluding_SharedBeforeEmpty,slantExcluding_SharedEmpty
1,R_0006zeOG7m4r5bX,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,-0.546900,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,R_000QQGgF1fS7UXL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.071429,0.000000,NaN,-0.049367,-0.049367,NaN,NaN,-0.049367,-0.049367,NaN
3,R_000QuLyZsff11wl,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,NaN,-0.257817,-0.344200,NaN,NaN,-0.257817,-0.344200,NaN
4,R_000vCzLW7tMEGbL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,-0.412733,-0.315225,NaN,NaN,-0.412733,-0.315225,NaN,NaN
5,R_001H4q0zrFzZ77H,1.0,3.0,3.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.500000,0.214286,0.395030,0.360139,0.372232,0.494269,0.425418,0.407814,0.428793,0.494269
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34588,R_zfeiEbwrxA57jrP,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,NaN,-0.535550,-0.535550,NaN,NaN,-0.524200,-0.524200,NaN
34589,R_zfiOvlmPfCMWNRn,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,NaN,-0.572300,NaN,NaN,NaN,-0.572300,NaN,NaN
34590,R_zfj2X1JcX4Yc2Qx,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,NaN,-0.398700,-0.309000,NaN,NaN,-0.398700,-0.309000,NaN
34591,R_zflZX23gkgzR2V3,15.0,6.0,1.0,1.0,0.0,0.0,0.0,0.0,15.0,...,0.000000,0.000000,-0.275300,-0.487490,-0.420567,-0.273500,-0.226020,-0.539533,-0.225750,NaN
34592,R_zfoOiBw3bx7UBB7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.142857,0.071429,0.608367,0.318837,0.235943,0.608367,0.608367,0.318837,0.235943,0.608367

In [27]:
all_user = pd.merge(left = fb_user, right = nav_his_user, how = "outer", on = "ResponseId")
all_user = pd.merge(left = all_user, right = shared_user, how = "outer", on = "ResponseId")
all_user = pd.merge(left = all_user, right = survey, how = "inner", on = "ResponseId")
all_user = pd.merge(left = all_user, right = like_user, how = "left", on = "ResponseId")

In [29]:
all_user.describe()

,potLibDay_FB,potLibDay_FBAd,potLibDay_FBFriend,potLibDay_FBPage,potConsDay_FB,potConsDay_FBAd,potConsDay_FBFriend,potConsDay_FBPage,potProDay_FB,potProDay_FBAd,...,F_slant_Dem,F_ideology,F_echoChamber,F_whoWillWin,F_vote,F_modifiedViews,potLib_Like,potCons_Like,potCounter_Like,potPro_Like
count,1835.000000,1835.000000,1835.000000,1835.000000,1835.000000,1835.000000,1835.000000,1835.000000,1835.000000,1835.000000,...,3.472800e+04,3.472800e+04,3.472800e+04,3.472800e+04,3.472800e+04,3.472800e+04,34618.000000,34618.000000,33558.000000,33558.000000
mean,3.147879,0.304788,0.841728,2.001362,1.006773,0.099299,0.128026,0.779447,3.078474,0.279330,...,-1.168662e+09,-1.169219e+09,-1.169528e+09,-1.150729e+09,-1.149369e+09,-1.156975e+09,0.350049,0.312294,0.253442,0.411318
std,8.603552,1.128415,1.820460,7.373353,4.277010,0.339585,0.313096,4.007859,8.580705,1.027472,...,1.069553e+09,1.069504e+09,1.069476e+09,1.070994e+09,1.071091e+09,1.070526e+09,0.919502,0.814420,0.722181,0.988620
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,0.000000,0.000000,0.000000,0.000000
50%,0.428571,0.000000,0.142857,0.071429,0.071429,0.000000,0.000000,0.000000,0.428571,0.000000,...,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,-2.147484e+09,0.000000,0.000000,0.000000,0.000000
75%,2.214286,0.142857,0.857143,0.571429,0.428571,0.071429,0.142857,0.071429,2.214286,0.142857,...,-2.000000e+00,-1.000000e+00,2.000000e+00,1.000000e+00,-1.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000
max,104.285714,20.500000,19.928571,100.214286,75.785714,6.857143,4.714286,68.785714,104.285714,20.500000,...,9.990000e+02,9.990000e+02,4.000000e+00,9.990000e+02,9.990000e+02,1.000000e+00,4.000000,4.000000,4.000000,4.000000